apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-10-25T03:18:54Z
  labels:
    run: "{{ .Release.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: "{{ .Chart.Name }}"
  namespace: tgl
  resourceVersion: "185385"
  selfLink: /api/v1/namespaces/default/services/example
  uid: b3ba91ac-d804-11e8-a2b3-080027a2c26e
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31100
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: "{{ .Release.Name }}"
  sessionAffinity: None
  type: "{{ .Values.service.type }}"
status:
  loadBalancer: {}
